services:
  agentzero:
    image: docker.io/frdel/agent-zero-run
    container_name: agent-zero
    volumes:
      - AgentZeroInstances:/a0
      - ${LOCAL_AGENT_DIR}/agent:/a0/work_dir
      - ./agent-zero/a0/tmp/settings.json:/a0/tmp/settings.json
      - ./agent-zero/a0/python/tools/knowledge_tool.py:/a0/python/tools/knowledge_tool.py
      - ./agent-zero/a0/python/helpers/perplexica.py:/a0/python/helpers/perplexica.py
      - ./agent-zero/a0/knowledge/default/main/about:/a0/knowledge/default/main/about
      # - ./agent-zero/a0/instruments/default:/a0/instruments/default
      - ./agent-zero/a0/settings.yml:/etc/searxng/settings.yml
    ports:
      - "50001:80"
    networks:
      - agent-network
    env_file:
      - ./agent-zero/.env
    depends_on:
      - ollama
      - perplexica-backend

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - OllamaModels:/root/.ollama/
    networks:
      - agent-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    env_file:
      - ./ollama/.env

  perplexica-backend:
    build:
      context: ./perplexica-874505c
      dockerfile: Dockerfile
    container_name: perplexica-backend
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    volumes:
      - Perplexica-DBstore:/home/perplexica/data
      - ./perplexica-874505c/config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - agent-network
    restart: unless-stopped

volumes:
  AgentZeroInstances:
    driver: local
  OllamaModels:
    driver: local
  Perplexica-DBstore:
    driver: local

networks:
  agent-network:
    driver: bridge
