services:
  agentzero:
    build: .
    container_name: agentzero_${INSTANCE_ID}
    privileged: true  # Enable privileged mode
    environment:
      - API_KEY_OPENAI=${API_KEY_OPENAI}
      - INSTANCE_ID=${INSTANCE_ID}
    volumes:
      - ${LOCAL_AGENT_DIR}:/app
    ports:
      - "${WEB_UI_PORT}:80" # Map the internal WebUI to port 80 of the container
      - "22:22" # Map for SSH throughput
    networks:
      - agent_network  # Network for intracontainer communication

networks:
  agent_network:
    driver: bridge
