services:
  agent-zero:
    image: docker.io/frdel/agent-zero-run:latest
    container_name: agent-zero
    volumes:
      - AgentZeroInstances:/a0
      - ${LOCAL_AGENT_DIR}/agent:/a0/work_dir
      - ./agent-zero/a0/tmp/settings.json:/a0/tmp/settings.json
      - ./agent-zero/a0/python/tools/knowledge_tool.py:/a0/python/tools/knowledge_tool.py
      - ./agent-zero/a0/python/helpers/perplexica.py:/a0/python/helpers/perplexica.py
      - ./agent-zero/a0/knowledge/default/main/about:/a0/knowledge/default/main/about
      - ./agent-zero/a0/instruments/custom:/a0/instruments/custom
      - ./agent-zero/searxng/limiter.toml:/etc/searxng/limiter.toml
      - ./agent-zero/searxng/settings.yml:/etc/searxng/settings.yml
      - ./agent-zero/searxng/uwsgi.ini:/etc/searxng/uwsgi.ini
    ports:
      - "50001:80"
    networks:
      - agent-network
    env_file:
      - ./agent-zero/.env
    # depends_on:
    #   - ollama

  # ollama:
  #   build:
  #     context: ./ollama
  #     dockerfile: Dockerfile
  #   container_name: ollama
  #   volumes:
  #     - OllamaModels:/root/.ollama/
  #   networks:
  #     - agent-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: ["gpu"]
  #   env_file:
  #     - ./ollama/.env

  perplexica-backend:
    container_name: perplexica-backend
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: ./perplexica/app.dockerfile
    environment:
      - SEARXNG_API_URL=http://agent-zero:8888
      - DATA_DIR=/home/perplexica
    ports:
      - 3000:3000   
    networks:
      - agent-network
    volumes:
      - Perplexica-DBstore:/home/perplexica/data
      - ./perplexica/config.toml:/home/perplexica/config.toml
    restart: unless-stopped

volumes:
  AgentZeroInstances:
    driver: local
  OllamaModels:
    driver: local
  Perplexica-DBstore:
    driver: local

networks:
  agent-network:
    driver: bridge

    

